[build]
  command = "npm run build"
  publish = "dist/spaseoapp-ng17-ssr-i18n-cypress/browser"
  functions = "netlify/functions"

[dev]
  command = "npm run serve:ssr:full"
  targetPort = 4000
  port = 8888
  autoLaunch = true

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

[[redirects]]
  from = "/thank-you"
  to = "/thank-you"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200